-- App quality guardrails:
-- - client telemetry tables (analytics + client-side errors)
-- - lightweight anti-spam rate limits for chat messages and snaps

begin;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint analytics_events_event_name_len_check check (char_length(event_name) between 1 and 120)
);

create table if not exists public.client_error_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  context text not null,
  error_name text not null,
  error_message text not null,
  stack text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint client_error_events_context_len_check check (char_length(context) between 1 and 200)
);

create index if not exists analytics_events_user_created_idx
  on public.analytics_events (user_id, created_at desc);

create index if not exists client_error_events_user_created_idx
  on public.client_error_events (user_id, created_at desc);

alter table public.analytics_events enable row level security;
alter table public.client_error_events enable row level security;

drop policy if exists "analytics_events_insert_own" on public.analytics_events;
drop policy if exists "analytics_events_select_own" on public.analytics_events;
create policy "analytics_events_insert_own"
  on public.analytics_events
  for insert
  to authenticated
  with check (user_id is null or user_id = auth.uid());
create policy "analytics_events_select_own"
  on public.analytics_events
  for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "client_error_events_insert_own" on public.client_error_events;
drop policy if exists "client_error_events_select_own" on public.client_error_events;
create policy "client_error_events_insert_own"
  on public.client_error_events
  for insert
  to authenticated
  with check (user_id is null or user_id = auth.uid());
create policy "client_error_events_select_own"
  on public.client_error_events
  for select
  to authenticated
  using (user_id = auth.uid());

create index if not exists chat_messages_sender_created_idx
  on public.chat_messages (sender_id, created_at desc);

create index if not exists snaps_sender_created_idx
  on public.snaps (sender_id, created_at desc);

create or replace function public.enforce_chat_message_rate_limit()
returns trigger
language plpgsql
as $$
declare
  recent_count integer;
begin
  if new.sender_id is null then
    return new;
  end if;

  select count(*)
    into recent_count
  from public.chat_messages m
  where m.sender_id = new.sender_id
    and m.created_at > now() - interval '20 seconds';

  if recent_count >= 20 then
    raise exception 'RATE_LIMIT_CHAT_MESSAGES'
      using errcode = 'P0001';
  end if;

  return new;
end;
$$;

create or replace function public.enforce_snap_rate_limit()
returns trigger
language plpgsql
as $$
declare
  recent_count integer;
begin
  if new.sender_id is null then
    return new;
  end if;

  select count(*)
    into recent_count
  from public.snaps s
  where s.sender_id = new.sender_id
    and s.created_at > now() - interval '60 seconds';

  if recent_count >= 12 then
    raise exception 'RATE_LIMIT_SNAPS'
      using errcode = 'P0001';
  end if;

  return new;
end;
$$;

drop trigger if exists chat_messages_rate_limit_before_insert on public.chat_messages;
create trigger chat_messages_rate_limit_before_insert
  before insert on public.chat_messages
  for each row
  execute function public.enforce_chat_message_rate_limit();

drop trigger if exists snaps_rate_limit_before_insert on public.snaps;
create trigger snaps_rate_limit_before_insert
  before insert on public.snaps
  for each row
  execute function public.enforce_snap_rate_limit();

comment on table public.analytics_events is
  'Client telemetry events for product analytics.';
comment on table public.client_error_events is
  'Client-side error reports sent by the app.';

commit;
